### ISSUE TITLE
Support requestBody (left side docs & sample code gen)

### ISSUE THREAD

**Issue by addshore** [enzonotario/vitepress-theme-openapi#10]
The component appears to know how to render JSON that matches the spec of the API responses

However it doesnt currenlty do this for JSON request bodys either in the docs (left side), or in the code samples.

e.g. for curl

```
curl -X POST "https://api.domain/v2/users/login" \
    -H "accept: application/json" \
    -H "content-type: application/json" \
    -d '{"refreshable":604800,"password":"","username":""}'
    ```

Generally recording this as an issue to track the things that I'd need in order to be able to fully make use of this component

**Comment by enzonotario** [comment]
Hi there! I've been working a little on this (just RequestBody, no CodeSamples), alongside the #3 . I'll finish it today or tomorrow and send changes.

**Comment by enzonotario** [comment]
It's now fixed for most cases (there may be cases with recursivity that might not work).
