### ISSUE TITLE
BUG: Parameters dont show in sample code, if only in:query

### ISSUE THREAD

**Issue by addshore** [enzonotario/vitepress-theme-openapi#11]
Currently parameters are rendered in the docs side (left side) however such parameters are not provided to easily copy and paste in the sample code

![image](https://github.com/user-attachments/assets/428447a5-0e59-4773-8a57-e0f7f2656dae)

This relates closely to https://github.com/enzonotario/vitepress-theme-openapi/issues/10 (for the sample code part)

**Comment by addshore** [comment]
Okay, coming back to this, I tried it with a second endpoint, and it seems to work

A paremeter such as this:

```
            {
              "name": "id",
              "in": "path",
              "description": "user id",
              "required": true,
              "schema": {
                "type": "string",
                "format": "JSON"
              }
            }
```

Results in something like this:

![image](https://github.com/user-attachments/assets/c3f3a357-7205-4f7d-a745-c4fbf73a0dfe)

However one only in the `query` doesnt result in the input field, or it existing in the sample

```
            {
              "name": "include",
              "in": "query",
              "required": true,
              "description": "Related objects to include in the response. See the description of return value for more details.",
              "schema": {
                "type": "string",
                "format": "JSON"
              }
            }
```

Results in 

![image](https://github.com/user-attachments/assets/509f5cc7-9d85-4b8e-a752-b9056707e010)


Adding a random PATH parmaeter such as this

```
            {
              "name": "foo",
              "in": "path",
              "required": true,
              "description": "Related objects to include in the response. See the description of return value for more details.",
              "schema": {
                "type": "string",
                "format": "JSON"
              }
            },
            {
              "name": "include",
              "in": "query",
              "required": true,
              "description": "Related objects to include in the response. See the description of return value for more details.",
              "schema": {
                "type": "string",
                "format": "JSON"
              }
            }
```

Seems to make the thing work

![image](https://github.com/user-attachments/assets/6380318f-1460-419e-9ad1-5a5a02698575)

**Comment by enzonotario** [comment]
It should be fixed now like in https://vitepress-theme-openapi.vercel.app/example/operations/get-users.html
