### ISSUE TITLE
BUG: samples dont respect method

### ISSUE THREAD

**Issue by addshore** [enzonotario/vitepress-theme-openapi#13]
Method appears correct in the "Try it out" section, but not in the samples

![image](https://github.com/user-attachments/assets/f5f5419d-c5f4-44e4-b4aa-0fbee58e2d95)

Screenshot was taken using this spec that demonstrates the issue https://gist.github.com/addshore/e6b973939739e25902025bf1667e69a1

**Comment by enzonotario** [comment]
I fixed it a bit, but it still doesn't support Body Editing, so the SampleCode for POST/PUT/etc is not real. I'm thinking on hiding it for now, it also should be done by an external library like:

- https://github.com/ErikWittern/openapi-snippet
- https://github.com/curlconverter/curlconverter.github.io

**Comment by addshore** [comment]
Ooh yeah, I think probably using an external library for this makes sense.
