### ISSUE TITLE
Request body field (display additional details)

### ISSUE THREAD

**Issue by addshore** [enzonotario/vitepress-theme-openapi#18]
My spec has a bunch of request property descriptions.

Something like this

```
{
  "properties": {
    "password": {
      "description": "Password of the user",
      "type": "string"
    },
    "refreshable": {
      "description": "Generate a refresh token, which expires this many seconds after the access token expiry. Max 31 days",
      "maximum": 2678400,
      "type": "integer"
    }
  }
}
```

Currently, the request body is just specified as a JSON blob

![image](https://github.com/user-attachments/assets/8f9a7e53-7869-4212-998e-5f666d22fdfe)

How do you think we could / should alter this to include details of descriptions, max, type etc

**Comment by enzonotario** [comment]
Here we should do basically the same as in ResponseBody, and improve the info that it shows for every property. 

In #20 I've separated an unified component `OASchemaBody` to be used in RequestBody/ResponseBody. Now we should improve the `OASchemaProperty` to show all Property attributes.

We also should find an appropriate way to show all this things. I've thinking in use Tabs to show the JSON Schema, but in the case of Responses it already has Tabs. 

Some docs I take inspirations are:

- https://developers.cloudflare.com/api/operations/health-checks-create-health-check
- https://docs.machines.dev/#tag/machines/get/apps/{app_name}/machines/{machine_id}
- https://fumadocs.vercel.app/docs/ui/museum/buy-museum-tickets
