### ISSUE TITLE
Enable rendering components for multiple specs on a single page.

### ISSUE THREAD

**Issue by addshore** [enzonotario/vitepress-theme-openapi#21]
Currently I have something like this on a single markdown page...

```
<script setup lang="ts">
import { useRoute, useData } from 'vitepress'
import { useSidebar, useOpenapi } from 'vitepress-theme-openapi'
import spec from '../swagger/v2.json' with { type: 'json' }
const openapi = useOpenapi()
openapi.setSpec(spec)
const route = useRoute()
const { isDark } = useData()
</script>

<OAOperation operationId="post-users-login" method="post" :isDark="isDark" />
<OAOperation operationId="post-users-refreshToken" method="post" :isDark="isDark" />
```

Further down the page I would like to include a component rendered from the `../swagger/v1.json` spec, however I believe with the current setup that will not be possible.

Ultimately I think this will require passing the openapi into the components? :)

**Comment by enzonotario** [comment]
Actually many components depends of an unique and global spec via `useOpenapi` composable, so it's not as easy to just pass an `:spec="spec"` prop to the `OAOperation` component.

So, i'd recommend you to just merge your specs into one, and adding the version as prefix for the `operationId`, so you could have something like:

```
<script setup lang="ts">
import { useRoute, useData } from 'vitepress'
import { useSidebar, useOpenapi } from 'vitepress-theme-openapi'
import specV2 from '../swagger/v2.json' with { type: 'json' }
import specV1 from '../swagger/v1.json' with { type: 'json' }
const openapi = useOpenapi()
openapi.setSpec({
  ...specV2,
  paths: {
    // merge them with something like this (not tested):
    ...specV2.paths.map((path, operationId) => ({
      [`v2-${operationId}`]: path
    })),
    ...specV1.paths.map((path, operationId) => ({
      [`v1-${operationId}`]: path
    }))
  },
})
const route = useRoute()
const { isDark } = useData()
</script>

<OAOperation operationId="v2-post-users-login" method="post" :isDark="isDark" />
<OAOperation operationId="v2-post-users-refreshToken" method="post" :isDark="isDark" />

<OAOperation operationId="v1-post-users-login" method="post" :isDark="isDark" />
<OAOperation operationId="v1-post-users-refreshToken" method="post" :isDark="isDark" />
```

Otherwise, it would require a re-design of most of the components.

**Comment by addshore** [comment]
I'll give this a go next week, and it could be mostly fine as the components focus on the routes.
In other displays of specs it could pose problems for example, as multiple / different definitions of schema (possibly with the same names) may exist, so they would need prefixing too.
Often displays of OAPI spec also for example show All of a type of thing in a list,
BUT as this library doesnt currently do any of that (and I for one am not even sure it should), then robably nothing to worry about!

**Comment by enzonotario** [comment]
Hi there! while working in some refactors, I realized that it can be possible and even better to separate the logics.

I'm working on it in #32 . Can you please check if it's working for you? There is also an example in https://vitepress-theme-openapi-git-featu-ca380b-enzo-notarios-projects.vercel.app/layouts/multiple-specs.html

**Comment by addshore** [comment]
Thanks, I'll aim to test it in the next few days!
