### ISSUE TITLE
Allow selection by path / key as well as / insead of operationId ?

### ISSUE THREAD

**Issue by addshore** [enzonotario/vitepress-theme-openapi#3]
> operationId is an optional unique string used to identify an operation. If provided, these IDs must be unique among all operations described in your API.

As a result my spec doesnt actually have `operationId` in it for each route
It would be great if route and method could be used in combination insead of operationId :)

**Comment by enzonotario** [comment]
Yes, but as you can see, this project is still in its early stages, so there are many missing features. For now, I recommend setting up an `operationId` for each operation and seeing if this project meets your needs. It works for my limited needs, so I’m not prioritizing further development at this time.

In fact, the "OpenAPI parser" (`useOpenapi` composable) is very limited and hand-crafted. I couldn’t find a well-suited parser that already existed, and creating one from scratch would be a long process, as the OpenAPI spec has many features.

Therefore, alongside this feature, there are many others that I’d prefer to address by finding an existing parser, allowing me to focus on components and VitePress integration.

PRs are welcome.

**Comment by addshore** [comment]
Sounds great, and I look forward to hopfully contributing moving forward.

For now while I'm trying it out I have slapped this in after loading my spec.

```
import spec from '../swagger/v2.json' with { type: 'json' }

spec.paths = Object.fromEntries(
  Object.entries(spec.paths).map(([path, value]) => {
    const method = Object.keys(value)[0]
    const operationId = `${method}${path.replace(/\//g, '-')}`
    value[method].operationId = operationId
    return [path, value]
  })
)
```

**Comment by enzonotario** [comment]
I just take it to do in every `setSpec`.. there still are many missing features, but at least works fine for most "read only APIs".

Thanks!
