### ISSUE TITLE
Tipo de respuesta 

### ISSUE THREAD

**Issue by fcoagz** [enzonotario/vitepress-theme-openapi#33]
Especifico el tipo de respuesta que retornara la petición, pero lo toma como un objeto.
![image](https://github.com/user-attachments/assets/fd8e8ce2-1220-4cc4-82c9-824ca8285f2f)
--
![image](https://github.com/user-attachments/assets/bb21bb58-e1e0-457e-ad88-f2107d8ee8e9)

**Comment by enzonotario** [comment]
Buenas! Si, actualmente la sección de "Probar" sólo está pensada para respuestas JSON.

Viene bien este Issue como seguimiento; intentaré trabajarlo en las próximas semanas, o también son bienvenidos los PRs .
