### ISSUE TITLE
Custom sidebar menu item link

### ISSUE THREAD

**Issue by addshore** [enzonotario/vitepress-theme-openapi#38]
I believe the currentl link prefix is hardcoded `link: `/operations/${c}``

However ultimately I would like to link to 2 different specs under 2 different URL prefixes, such as...
 - `http://localhost:5173/apis/v2/`
 - `http://localhost:5173/apis/v1/`

To do this I guess I would need to pass a prefix into the methods such as `generateSidebarGroup`

My current code is:

```
            {
              text: 'Version 2',
              link: '/apis/v2',
              items: [
                sidebar.generateSidebarGroup(["users", "published"],"Users"),
              ],
            },
```

**Comment by enzonotario** [comment]
Yes, it is hardcoded, and it's a good idea to make it configurable (we'll work on #41 and #44).

However, I'd like to point out that `useSidebar` simply returns an array, which we can always `map` over and transform as needed (see https://github.com/enzonotario/esjs-argentina-datos-api/blob/16d7208f7644accc8b0aa9b957cb643fade578d2/docs/.vitepress/config.ts#L14)

**Comment by addshore** [comment]
> However, I'd like to point out that useSidebar simply returns an array, which we can always map over and transform as needed (see https://github.com/enzonotario/esjs-argentina-datos-api/blob/16d7208f7644accc8b0aa9b957cb643fade578d2/docs/.vitepress/config.ts#L14)

Indeed, I actually now also do this to default all groups to be collapsed by default.
However, customizable link prefix I think is a nice thing to add to the methods as is :)
Thanks for the modified PR!
