### ISSUE TITLE
Support body for "try it out"

### ISSUE THREAD

**Issue by addshore** [enzonotario/vitepress-theme-openapi#42]
Follow on to https://github.com/enzonotario/vitepress-theme-openapi/issues/10

It would be great to allow trying out requests that have a body required.

Probably a first version of this would just provide a single text input box for the whole "body" to be provided.

Users could then easily copy and paste the example (probably json) body, and modify it

**Comment by enzonotario** [comment]
I've added support for this. You may want to use it as `useTheme().setPlaygroundJsonEditorMode('text')`, but I setted it as `tree` by default.

There are many things we can improve here:

- A form view using [shadcn-vue AutoForm](https://www.shadcn-vue.com/docs/components/auto-form)
- A new layout with 1 column, where the "Try" section is integrated with the content of the current Left Column, allowing to just edit the current "Request Body" section

Thanks!

**Comment by addshore** [comment]
Just tried it, and it works very well!!!
