### ISSUE TITLE
Working example with search provider local set

### ISSUE THREAD

**Issue by addshore** [enzonotario/vitepress-theme-openapi#47]
On my site I have the following in my vitepress config

```
    search: {
      provider: 'local'
    }
```

per https://vitepress.dev/reference/default-theme-search

However, pages rendered via the method suggested `*.paths.js` doesnt appear in the search.

![image](https://github.com/user-attachments/assets/2069feb5-281b-4171-a5c3-0abac2b8323e)

Seemingly none of the example sites currently include search, and thus the component doesnt appear to work with search?

**Comment by enzonotario** [comment]
I think it depends more on VitePress (see https://github.com/vuejs/vitepress/issues/2939)

Can you please check if it works with [vitepress-plugin-pagefind](https://www.npmjs.com/package/vitepress-plugin-pagefind).

**Comment by addshore** [comment]
Yes, this appears to work well, (not while running the dev server) but that is fine!

![image](https://github.com/user-attachments/assets/0ee040e7-7b66-4ed8-b93d-e794f12cd115)
