### ISSUE TITLE
[Feature] Site-wide authentication

### ISSUE THREAD

**Issue by JustSamuel** [enzonotario/vitepress-theme-openapi#59]
### What would you like?

Swagger-ui has the option to set a token once for the site and have it be used for every test api call. Maybe such an option would also be nice for the openapi theme.

### Why is this needed?

Makes it a bit friendlier to use as you do not need to constantly insert a bearer token.

### How could it be implemented?

Similarly to how swagger-ui does it. Have a global button which stores the authentication method / value.

**Comment by enzonotario** [comment]
I worked on it in #62. Can you please validate it?
